---
  logzio:
    token: TOKEN

  files:
    -
      type: "mylogtype"
      logzio_codec: "plain"
      path: "/var/log/logfile.log"
      multiline:
        pattern: "^\\[?[[:digit:]]+[\\-\\/][[:digit:]]+[\\-\\/][[:digit:]]+ [[:digit:]]+:[[:digit:]]+:[[:digit:]]+"
    -
      type: "anothertype-json"
      logzio_codec: "json"
      path: "/var/log/another-json-log.log"
